/**
 * MCP Notification Handler — Deterministic
 *
 * Handles queue/new and comment/created notifications from MCP SSE.
 * Mechanical steps (accept, read, post) are done directly via mcpClientPool.
 * Only the response text is generated by the LLM.
 */

import { mcpClientPool } from "./client.js";
import {
  createSession,
  sendMessage,
  listSessions,
} from "../../conversations/index.js";

interface ActiveAgent {
  agentId: string;
  adapterSlug: string;
  sessionId: string;
  unsubscribe: (() => void) | null;
  presenceInterval: ReturnType<typeof setInterval> | null;
  busy: boolean;
  lastHandledCommentId: string | null; // dedup
}

const activeAgents = new Map<string, ActiveAgent>();

export function activateNotifications(
  agentId: string,
  adapterSlug: string
): void {
  if (activeAgents.has(agentId)) return;

  // Ensure SSE listener is open for this adapter
  mcpClientPool.ensureSseListener(adapterSlug);

  const sessions = listSessions("system", agentId);
  let sessionId: string;
  if (sessions.length > 0) {
    sessionId = sessions[sessions.length - 1].session_id;
  } else {
    const session = createSession("system", agentId);
    sessionId = session.session_id;
  }

  const unsubscribe = mcpClientPool.onNotification(
    (slug, method, params) => {
      if (slug !== adapterSlug) return;
      handleNotification(agentId, adapterSlug, method, params);
    }
  );

  // Presence heartbeat: refresh TTL every 55s (no LLM, just HTTP)
  const presenceInterval = setInterval(async () => {
    try {
      await mcpClientPool.callTool(adapterSlug, "presence_heartbeat", {}, agentId);
    } catch {
      try {
        await mcpClientPool.callTool(adapterSlug, "presence_online", { limit: 5 }, agentId);
      } catch {
        console.warn(`[mcp-notify] presence refresh failed for ${agentId}`);
      }
    }
  }, 55_000);

  activeAgents.set(agentId, {
    agentId,
    adapterSlug,
    sessionId,
    unsubscribe,
    presenceInterval,
    busy: false,
    lastHandledCommentId: null,
  });

  console.log(
    `[mcp-notify] activated for ${agentId} (session=${sessionId}, adapter=${adapterSlug})`
  );
}

export function deactivateNotifications(agentId: string): void {
  const entry = activeAgents.get(agentId);
  if (!entry) return;
  if (entry.presenceInterval) clearInterval(entry.presenceInterval);
  if (entry.unsubscribe) entry.unsubscribe();
  activeAgents.delete(agentId);
  console.log(`[mcp-notify] deactivated for ${agentId}`);
}

export function isNotificationActive(agentId: string): boolean {
  return activeAgents.has(agentId);
}

// --- Internal ---

function handleNotification(
  agentId: string,
  adapterSlug: string,
  method: string,
  params: Record<string, unknown>
): void {
  if (method === "notifications/queue/new") {
    const threadId = params.threadId as string;
    handleQueueNew(agentId, adapterSlug, threadId);
  } else if (method === "notifications/comment/created") {
    const authorType = params.authorType as string;
    if (authorType === "customer") {
      const threadId = params.threadId as string;
      const commentId = params.commentId as string;
      handleCommentCreated(agentId, adapterSlug, threadId, commentId);
    }
  } else if (method === "notifications/queue/taken") {
    const threadId = params.threadId as string;
    console.log(`[mcp-notify] queue/taken: ${threadId} (another attendant)`);
  }
}

/**
 * queue/new: accept chat, read message, generate response, post it
 */
async function handleQueueNew(
  agentId: string,
  adapterSlug: string,
  threadId: string
): Promise<void> {
  const entry = activeAgents.get(agentId);
  if (!entry) return;

  if (entry.busy) {
    // Don't retry queue/new — if we're busy, another attendant can take it
    console.log(`[mcp-notify] ${agentId} busy, skipping queue/new for ${threadId}`);
    return;
  }

  entry.busy = true;
  console.log(`[mcp-notify] queue/new: accepting thread ${threadId}`);

  try {
    // Step 1: Accept the chat
    const acceptResult = await mcpClientPool.callTool(
      adapterSlug, "queue_accept", { thread_id: threadId }, agentId
    ) as any;

    const acceptText = acceptResult?.content?.[0]?.text ?? JSON.stringify(acceptResult);
    if (acceptText.includes('"error"')) {
      console.log(`[mcp-notify] queue_accept failed: ${acceptText}`);
      return;
    }
    console.log(`[mcp-notify] accepted thread ${threadId}`);

    // Step 2: Read customer message (with retry — comment may not be persisted yet)
    let customerMessage = "";
    for (let attempt = 0; attempt < 5; attempt++) {
      if (attempt > 0) await new Promise(r => setTimeout(r, 500));
      const comments = await readComments(adapterSlug, threadId, agentId);
      customerMessage = comments.find((c: any) => c.author_type === "customer")?.text ?? "";
      if (customerMessage) break;
    }

    if (!customerMessage) {
      console.warn(`[mcp-notify] no customer message found in thread ${threadId} after 5 retries`);
      return;
    }
    console.log(`[mcp-notify] customer said: ${customerMessage.slice(0, 80)}...`);

    // Step 3: Ask LLM to generate response
    const llmPrompt = `Voce eh Kai, suporte tecnico da Processa Sistemas. Um cliente abriu um chat ao vivo pedindo ajuda.

O cliente disse: "${customerMessage}"

Escreva a resposta que voce daria ao cliente. A resposta vai ser enviada diretamente para ele no chat ao vivo.

Instrucoes:
1. Cumprimente e identifique-se como Kai do suporte tecnico
2. Demonstre que entendeu o problema
3. Faca 2-3 perguntas especificas de diagnostico para entender melhor a situacao
4. Se possivel, de uma orientacao inicial ou workaround

Importante:
- Use texto sem acentos (restricao temporaria de encoding)
- Escreva 3-5 paragrafos
- Seja acolhedora e profissional
- NAO use tools, NAO use markdown — texto puro`;

    const responseText = await getLlmResponse(agentId, entry.sessionId, llmPrompt);
    if (!responseText || isBlockedResponse(responseText)) {
      console.warn(`[mcp-notify] LLM response blocked/empty for thread ${threadId}: ${responseText?.slice(0, 60)}`);
      return;
    }
    console.log(`[mcp-notify] LLM response: ${responseText.slice(0, 80)}...`);

    // Step 4: Post response to Coletivos
    const postResult = await mcpClientPool.callTool(
      adapterSlug, "create_comment",
      { thread_id: threadId, text: responseText, visibility: "public" },
      agentId
    ) as any;

    // Track last comment ID for dedup
    try {
      const posted = JSON.parse(postResult?.content?.[0]?.text ?? "{}");
      if (posted.id) entry.lastHandledCommentId = posted.id;
    } catch { /* ignore */ }

    console.log(`[mcp-notify] response posted to thread ${threadId}`);

  } catch (err) {
    console.error(`[mcp-notify] handleQueueNew failed:`, err);
  } finally {
    entry.busy = false;
  }
}

/**
 * comment/created: read new message, generate response, post it.
 * Includes dedup and closure detection.
 */
async function handleCommentCreated(
  agentId: string,
  adapterSlug: string,
  threadId: string,
  commentId: string
): Promise<void> {
  const entry = activeAgents.get(agentId);
  if (!entry) return;

  // Dedup: skip if we already handled this comment
  if (entry.lastHandledCommentId === commentId) {
    console.log(`[mcp-notify] dedup: already handled comment ${commentId}`);
    return;
  }

  if (entry.busy) {
    // Retry once after delay
    console.log(`[mcp-notify] ${agentId} busy, retrying comment/created in 5s`);
    setTimeout(() => {
      if (entry.lastHandledCommentId !== commentId) {
        handleCommentCreated(agentId, adapterSlug, threadId, commentId);
      }
    }, 5_000);
    return;
  }

  entry.busy = true;
  entry.lastHandledCommentId = commentId; // mark as handling
  console.log(`[mcp-notify] comment/created: reading thread ${threadId}`);

  try {
    // Step 1: Read all comments
    const comments = await readComments(adapterSlug, threadId, agentId);

    // Dedup: check if last comment is already ours
    const lastComment = comments[comments.length - 1];
    if (lastComment?.author_type !== "customer") {
      console.log(`[mcp-notify] last comment is not from customer — skipping`);
      return;
    }

    // Build conversation history
    const history = comments.map((c: any) =>
      `${c.author_type === "customer" ? "Cliente" : "Kai"}: ${c.text}`
    ).join("\n\n");

    const lastCustomerMsg = lastComment.text ?? "";
    console.log(`[mcp-notify] customer replied: ${lastCustomerMsg.slice(0, 80)}...`);

    // Step 2: Ask LLM to generate response (with closure detection)
    const llmPrompt = `Voce eh Kai, suporte tecnico da Processa Sistemas. Voce esta em um chat ao vivo com um cliente.

Historico completo do chat:
${history}

O cliente acabou de dizer: "${lastCustomerMsg}"

Escreva a resposta. A resposta vai ser enviada diretamente para o cliente.

Instrucoes:
- Continue o atendimento com base no historico
- Se voce consegue resolver o problema, de a solucao
- Se precisa escalar para o time de desenvolvimento, informe o cliente
- Se o problema parece resolvido e o cliente esta satisfeito, se despeca e diga que o chamado sera registrado para acompanhamento
- Se o problema precisa de investigacao, explique os proximos passos

IMPORTANTE — ao final da sua resposta, adicione uma linha separada com um dos seguintes codigos:
- [CONTINUAR] se o atendimento deve continuar (mais perguntas, mais diagnostico)
- [ENCERRAR] se o atendimento pode ser encerrado (problema resolvido, escalado, ou cliente satisfeito)

Exemplo:
"Entendi o problema... vou encaminhar para o time...

[ENCERRAR]"

Regras:
- Texto sem acentos (restricao temporaria)
- 2-5 paragrafos
- Seja acolhedora e profissional
- NAO use tools, NAO use markdown — texto puro`;

    const responseText = await getLlmResponse(agentId, entry.sessionId, llmPrompt);
    if (!responseText || isBlockedResponse(responseText)) {
      console.warn(`[mcp-notify] LLM response blocked/empty for thread ${threadId}`);
      return;
    }

    // Parse closure signal
    const shouldClose = responseText.includes("[ENCERRAR]");
    const cleanResponse = responseText.replace(/\[CONTINUAR\]|\[ENCERRAR\]/g, "").trim();

    console.log(`[mcp-notify] LLM response (close=${shouldClose}): ${cleanResponse.slice(0, 80)}...`);

    // Step 3: Post response
    const postResult = await mcpClientPool.callTool(
      adapterSlug, "create_comment",
      { thread_id: threadId, text: cleanResponse, visibility: "public" },
      agentId
    ) as any;

    try {
      const posted = JSON.parse(postResult?.content?.[0]?.text ?? "{}");
      if (posted.id) entry.lastHandledCommentId = posted.id;
    } catch { /* ignore */ }

    console.log(`[mcp-notify] response posted to thread ${threadId}`);

    // Step 4: Close thread if LLM signaled closure
    if (shouldClose) {
      console.log(`[mcp-notify] closing thread ${threadId}`);

      // Build summary for the issue
      const summary = comments.map((c: any) =>
        `${c.author_type === "customer" ? "Cliente" : "Atendente"}: ${c.text}`
      ).join("\n").slice(0, 500);

      await mcpClientPool.callTool(
        adapterSlug, "end_chat_session",
        { thread_id: threadId, reason: summary },
        agentId
      );
      console.log(`[mcp-notify] chat session ended for ${threadId} — thread becomes async issue`);
    }

  } catch (err) {
    console.error(`[mcp-notify] handleCommentCreated failed:`, err);
  } finally {
    entry.busy = false;
  }
}

// --- Helpers ---

async function readComments(
  adapterSlug: string,
  threadId: string,
  agentId: string
): Promise<any[]> {
  const result = await mcpClientPool.callTool(
    adapterSlug, "list_comments", { thread_id: threadId }, agentId
  ) as any;
  const text = result?.content?.[0]?.text ?? "[]";
  return JSON.parse(text);
}

const BLOCKED_RESPONSES = [
  "mensagem nao permitida",
  "sistema de seguranca",
  "agente pausado",
  "limite de quota",
];

function isBlockedResponse(text: string): boolean {
  const lower = text.toLowerCase();
  return BLOCKED_RESPONSES.some(b => lower.includes(b));
}

async function getLlmResponse(
  agentId: string,
  sessionId: string,
  prompt: string
): Promise<string | null> {
  let fullText = "";
  try {
    for await (const event of sendMessage("system", sessionId, prompt)) {
      if (event.type === "result" && event.content) {
        fullText = event.content as string;
      } else if (event.type === "text" && event.content) {
        fullText += event.content;
      }
    }
  } catch (err) {
    console.error(`[mcp-notify] getLlmResponse failed:`, err);
    return null;
  }
  return fullText || null;
}
