active-plan: economic
web-search:
  provider: brave
menu:
  contexts:
    main:
      workflows: false
      inbox: false
      aprovacoes: false
      analytics: false
      ratings: false
      seguranca: false
      conformidade: false
      fleet: false
      opentelemetry: false
    agent:
      knowledge: true
      versoes: false
      quotas: false
      conformidade: false
      circuit_breaker: false
      avaliacao: false
      qualidade: false
      benchmarks: false
infrastructure:
  ngrok:
    authtoken: ENC(UVKPnUVOQKWugm14YgJmAG72wysjuPeS6gMNvo3UHIZHVQlxRj6RX0/PMyPZdN6UQgwA5mBXdT2QoJ/JwI51Rcis1odbAB2lFQyLdQA=)
    domain: nonporphyritic-microcrystalline-kenya.ngrok-free.dev
    enabled: true
  whisper:
    model: small
    compute-type: int8
providers:
  openrouter:
    api_key: ENC(zQ4Pgmoq0OANjHSxPd8/2nzUkgNb4Ez8N5ZjczDAbybBXULC7RMI7pkVEqc3C3yUfjPLGAO8DCZINJ71ZoMCI8bi/X9AeYs10EP3JQx1A3IIJIbSKDAf+B0BdYQi/TMK3AUAhq4=)
  openai:
    api_key: ENC(EGtnl+P4qHxrPG/nfjYqpKiU95tHDgT+DhpCh6Yj4I4CcO67txw9eReq3LUyPtiOWkRoixBCrguEYCdJMmnGtwOxWIL09fM6WylgC6JEw14kc7SRuiJQbeS4shz6XmIwVDtwiSK9amTr99MVVM6/SBTJwigOhXzCwniFWFcp1MRA/BiRL5GKsFkvt2pSqaXrTBvGfIGULqs+4Af1DsCp0EP+sJ1wXOizF/rD8eSZiDiBBmhfkZehYwdowFoKeX2B)
  brave:
    api_key: ENC(yaEzpkB5L6mm1+KJ6Sw/cCZKFDcXZqzqlt+DXJ1M/xOYNIDbf4dBiHkq/ajX2sVmgz+Efb53GfuI1ng=)
