active-plan: premium
security:
  message-filter: false
web-search:
  provider: brave
menu:
  contexts:
    main:
      workflows: false
      inbox: false
      aprovacoes: false
      analytics: false
      ratings: false
      seguranca: false
      conformidade: false
      fleet: false
      opentelemetry: false
    agent:
      knowledge: true
      versoes: false
      quotas: false
      conformidade: false
      circuit_breaker: false
      avaliacao: false
      qualidade: false
      benchmarks: false
infrastructure:
  ngrok:
    authtoken: ENC(YA2H6ghEzc2KP8IkXC8+a08gCjuMqQvNR8Hl5etKTd/9tbqLsuwvBKVjHMpcRi5Ijtbd+ShPRhZjM4rhgaCodh+D1QmHRrMuPB4xFBQ=)
    domain: nonporphyritic-microcrystalline-kenya.ngrok-free.dev
    enabled: true
  whisper:
    model: small
    compute-type: int8
providers:
  openrouter:
    api_key: ENC(l2S+GzQMrV0tTSAWeY295646kzZA7vyBqsbHx0V/oIsufhlNdX0VcD7XeaGaVT5p/PZqBUP7HBisnOSYgw9XdLdSFCLlScKdYPE2Lffy8ZhmFx0bs360mLQ82erD1ilYk3V29/4=)
  openai:
    api_key: ENC(HClni5wZRZcsLMjv0DlAuoE10zBMnNzJrQ3NPW+POvmRpe4ullW/xbJtGTJfzbAQL1LcoYe/1kuWJ0BeuUmVXo/ASkVxdVm/LhfiMhItUD7FH4ZTwPTtBpV+XZC9ebmupRv6DYrmKWgphfEQDoKG8nVAV896TxbQAOjGrqLq4opxLnvOtJW7D3xeSmJcfydQQFDJLYvJqZv8csdz9H7Tqg4zwtrbBcjScKfFZmTH1dsFZ8ZEEBLCuPzdpcKPh0YR)
  brave:
    api_key: ENC(iQo8r52rOiTdmZAHebGQnPGFTBTl/Ft+8I++2bA3WnVqTe11uiQCzaQLaJHLr+VEkXxPbTV+aQ0nlv4=)
