active-plan: free
security:
  message-filter: false
web-search:
  provider: brave
menu:
  contexts:
    main:
      workflows: false
      inbox: false
      aprovacoes: false
      analytics: false
      ratings: false
      seguranca: false
      conformidade: false
      fleet: false
      opentelemetry: false
    agent:
      knowledge: true
      versoes: false
      quotas: false
      conformidade: false
      circuit_breaker: false
      avaliacao: false
      qualidade: false
      benchmarks: false
infrastructure:
  ngrok:
    authtoken: ENC(Fzinhbbkzo6ccJ6CPv+otov1TiG17KulrypUd67QejTYwUYRso7FSB031G5A+1GwBA5D/9OYJI/7y8wlGCItkw9CiyCuRyXmRUPBD4A=)
    domain: nonporphyritic-microcrystalline-kenya.ngrok-free.dev
    enabled: true
  whisper:
    model: small
    compute-type: int8
providers:
  openrouter:
    api_key: ENC(IOY0YS3CG9hx4KKyoLdt1YUP/o1Bt60gdS389GUXI1UkXoK4hSWULwCt9e/RBSiRDSwSFCSJ6bzADUpzdF3jh1ybE/E6hOE7ZGkATf1mSd+FX3t/AweoXIR16uLtg0WiiiFrI5I=)
  openai:
    api_key: ENC(pjsNC0t7PUANXTaTeoB6mWtsTO8Tx69rU87idyAZBoWhlOT9+5aLlAKMG2ADzQp+L9tHrDSLEQytysNFVvSY2qol1yp417GJuleXCGVLmj+KtXd1e0yJM2MK0AWT37GKw8pazTCrPlaA73ZHGnHcx6y4qTdgok5Pe67j+4auol4eOCQc6FNU5akci9UcKorGCAWj1wceN7r1ACt5qLZAAFSPbQ5Glc0tgPqHvzpdtp2VQ9dmjjDAa52jjsbGIFwN)
  brave:
    api_key: ENC(Z8NRY2Q8UWi9WXsYq7qX2NGEmrTgUkNgmCHmDRBsm6jSBsAWzZwbaasPsLTc5R2J8EzCGq+Gve6xHWs=)
  groq:
    api_key: ENC(aoUUJ75KzhkxPgjBi9BfoyfMru6enYXghBl0CItdV+WDYX0fHnAw3tmwl4xQzcfzoWg7Fs6qIegubOuUU4YqV4zOHUjVsE5bywGGMGjwj9n4OBTJ)
