/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedTranscriptionRouteImport } from './routes/_authenticated/transcription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRatingsRouteImport } from './routes/_authenticated/ratings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedCronRouteImport } from './routes/_authenticated/cron'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAdaptersRouteImport } from './routes/_authenticated/adapters'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security/index'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedFleetIndexRouteImport } from './routes/_authenticated/fleet/index'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels/index'
import { Route as AuthenticatedApprovalsIndexRouteImport } from './routes/_authenticated/approvals/index'
import { Route as AuthenticatedAdaptersIndexRouteImport } from './routes/_authenticated/adapters/index'
import { Route as AuthenticatedWorkflowsNewRouteImport } from './routes/_authenticated/workflows/new'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows.$id'
import { Route as AuthenticatedSettingsOtelRouteImport } from './routes/_authenticated/settings_.otel'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedConversationsNewRouteImport } from './routes/_authenticated/conversations/new'
import { Route as AuthenticatedConversationsIdRouteImport } from './routes/_authenticated/conversations/$id'
import { Route as AuthenticatedChannelsNewRouteImport } from './routes/_authenticated/channels/new'
import { Route as AuthenticatedChannelsSlugRouteImport } from './routes/_authenticated/channels.$slug'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAdaptersNewRouteImport } from './routes/_authenticated/adapters/new'
import { Route as AuthenticatedAgentsIdIndexRouteImport } from './routes/_authenticated/agents.$id.index'
import { Route as AuthenticatedSettingsUsersSlugRouteImport } from './routes/_authenticated/settings_.users.$slug'
import { Route as AuthenticatedAgentsIdWorkflowsRouteImport } from './routes/_authenticated/agents.$id.workflows'
import { Route as AuthenticatedAgentsIdWebhooksRouteImport } from './routes/_authenticated/agents.$id.webhooks'
import { Route as AuthenticatedAgentsIdVersionsRouteImport } from './routes/_authenticated/agents.$id.versions'
import { Route as AuthenticatedAgentsIdSandboxRouteImport } from './routes/_authenticated/agents.$id.sandbox'
import { Route as AuthenticatedAgentsIdRoutingRouteImport } from './routes/_authenticated/agents.$id.routing'
import { Route as AuthenticatedAgentsIdRatingsRouteImport } from './routes/_authenticated/agents.$id.ratings'
import { Route as AuthenticatedAgentsIdQuotasRouteImport } from './routes/_authenticated/agents.$id.quotas'
import { Route as AuthenticatedAgentsIdQualityRouteImport } from './routes/_authenticated/agents.$id.quality'
import { Route as AuthenticatedAgentsIdMemoryRouteImport } from './routes/_authenticated/agents.$id.memory'
import { Route as AuthenticatedAgentsIdMcpToolsRouteImport } from './routes/_authenticated/agents.$id.mcp-tools'
import { Route as AuthenticatedAgentsIdKnowledgeRouteImport } from './routes/_authenticated/agents.$id.knowledge'
import { Route as AuthenticatedAgentsIdHandoffsRouteImport } from './routes/_authenticated/agents.$id.handoffs'
import { Route as AuthenticatedAgentsIdEvaluationRouteImport } from './routes/_authenticated/agents.$id.evaluation'
import { Route as AuthenticatedAgentsIdCronRouteImport } from './routes/_authenticated/agents.$id.cron'
import { Route as AuthenticatedAgentsIdConversationsRouteImport } from './routes/_authenticated/agents.$id.conversations'
import { Route as AuthenticatedAgentsIdConfigRouteImport } from './routes/_authenticated/agents.$id.config'
import { Route as AuthenticatedAgentsIdComplianceRouteImport } from './routes/_authenticated/agents.$id.compliance'
import { Route as AuthenticatedAgentsIdCircuitBreakerRouteImport } from './routes/_authenticated/agents.$id.circuit-breaker'
import { Route as AuthenticatedAgentsIdChannelsRouteImport } from './routes/_authenticated/agents.$id.channels'
import { Route as AuthenticatedAgentsIdBenchmarksRouteImport } from './routes/_authenticated/agents.$id.benchmarks'
import { Route as AuthenticatedSettingsUsersSlugIndexRouteImport } from './routes/_authenticated/settings_.users.$slug.index'
import { Route as AuthenticatedAgentsIdConversationsIndexRouteImport } from './routes/_authenticated/agents.$id.conversations.index'
import { Route as AuthenticatedSettingsUsersSlugPasswordRouteImport } from './routes/_authenticated/settings_.users.$slug.password'
import { Route as AuthenticatedAgentsIdEvalRunsRunIdRouteImport } from './routes/_authenticated/agents.$id.eval-runs.$runId'
import { Route as AuthenticatedAgentsIdDraftsDraftIdRouteImport } from './routes/_authenticated/agents.$id.drafts.$draftId'
import { Route as AuthenticatedAgentsIdConversationsConvIdRouteImport } from './routes/_authenticated/agents.$id.conversations.$convId'
import { Route as AuthenticatedAgentsIdBenchmarksRunIdRouteImport } from './routes/_authenticated/agents.$id.benchmarks.$runId'
import { Route as AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport } from './routes/_authenticated/agents.$id.drafts.$draftId.compare'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTranscriptionRoute =
  AuthenticatedTranscriptionRouteImport.update({
    id: '/transcription',
    path: '/transcription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatingsRoute = AuthenticatedRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCronRoute = AuthenticatedCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdaptersRoute = AuthenticatedAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetIndexRoute = AuthenticatedFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedApprovalsIndexRoute =
  AuthenticatedApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdaptersIndexRoute =
  AuthenticatedAdaptersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdaptersRoute,
  } as any)
const AuthenticatedWorkflowsNewRoute =
  AuthenticatedWorkflowsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedSettingsOtelRoute =
  AuthenticatedSettingsOtelRouteImport.update({
    id: '/settings_/otel',
    path: '/settings/otel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedConversationsNewRoute =
  AuthenticatedConversationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedConversationsIdRoute =
  AuthenticatedConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedChannelsNewRoute =
  AuthenticatedChannelsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsSlugRoute =
  AuthenticatedChannelsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAdaptersNewRoute =
  AuthenticatedAdaptersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdaptersRoute,
  } as any)
const AuthenticatedAgentsIdIndexRoute =
  AuthenticatedAgentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedSettingsUsersSlugRoute =
  AuthenticatedSettingsUsersSlugRouteImport.update({
    id: '/settings_/users/$slug',
    path: '/settings/users/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsIdWorkflowsRoute =
  AuthenticatedAgentsIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdWebhooksRoute =
  AuthenticatedAgentsIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdVersionsRoute =
  AuthenticatedAgentsIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdSandboxRoute =
  AuthenticatedAgentsIdSandboxRouteImport.update({
    id: '/sandbox',
    path: '/sandbox',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdRoutingRoute =
  AuthenticatedAgentsIdRoutingRouteImport.update({
    id: '/routing',
    path: '/routing',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdRatingsRoute =
  AuthenticatedAgentsIdRatingsRouteImport.update({
    id: '/ratings',
    path: '/ratings',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdQuotasRoute =
  AuthenticatedAgentsIdQuotasRouteImport.update({
    id: '/quotas',
    path: '/quotas',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdQualityRoute =
  AuthenticatedAgentsIdQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdMemoryRoute =
  AuthenticatedAgentsIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdMcpToolsRoute =
  AuthenticatedAgentsIdMcpToolsRouteImport.update({
    id: '/mcp-tools',
    path: '/mcp-tools',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdKnowledgeRoute =
  AuthenticatedAgentsIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdHandoffsRoute =
  AuthenticatedAgentsIdHandoffsRouteImport.update({
    id: '/handoffs',
    path: '/handoffs',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdEvaluationRoute =
  AuthenticatedAgentsIdEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdCronRoute =
  AuthenticatedAgentsIdCronRouteImport.update({
    id: '/cron',
    path: '/cron',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdConversationsRoute =
  AuthenticatedAgentsIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdConfigRoute =
  AuthenticatedAgentsIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdComplianceRoute =
  AuthenticatedAgentsIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdCircuitBreakerRoute =
  AuthenticatedAgentsIdCircuitBreakerRouteImport.update({
    id: '/circuit-breaker',
    path: '/circuit-breaker',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdChannelsRoute =
  AuthenticatedAgentsIdChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdBenchmarksRoute =
  AuthenticatedAgentsIdBenchmarksRouteImport.update({
    id: '/benchmarks',
    path: '/benchmarks',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedSettingsUsersSlugIndexRoute =
  AuthenticatedSettingsUsersSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsUsersSlugRoute,
  } as any)
const AuthenticatedAgentsIdConversationsIndexRoute =
  AuthenticatedAgentsIdConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdConversationsRoute,
  } as any)
const AuthenticatedSettingsUsersSlugPasswordRoute =
  AuthenticatedSettingsUsersSlugPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsUsersSlugRoute,
  } as any)
const AuthenticatedAgentsIdEvalRunsRunIdRoute =
  AuthenticatedAgentsIdEvalRunsRunIdRouteImport.update({
    id: '/eval-runs/$runId',
    path: '/eval-runs/$runId',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdDraftsDraftIdRoute =
  AuthenticatedAgentsIdDraftsDraftIdRouteImport.update({
    id: '/drafts/$draftId',
    path: '/drafts/$draftId',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdConversationsConvIdRoute =
  AuthenticatedAgentsIdConversationsConvIdRouteImport.update({
    id: '/$convId',
    path: '/$convId',
    getParentRoute: () => AuthenticatedAgentsIdConversationsRoute,
  } as any)
const AuthenticatedAgentsIdBenchmarksRunIdRoute =
  AuthenticatedAgentsIdBenchmarksRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthenticatedAgentsIdBenchmarksRoute,
  } as any)
const AuthenticatedAgentsIdDraftsDraftIdCompareRoute =
  AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedAgentsIdDraftsDraftIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/adapters': typeof AuthenticatedAdaptersRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/costs': typeof AuthenticatedCostsRoute
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transcription': typeof AuthenticatedTranscriptionRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/adapters/new': typeof AuthenticatedAdaptersNewRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/channels/new': typeof AuthenticatedChannelsNewRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/conversations/new': typeof AuthenticatedConversationsNewRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/settings/otel': typeof AuthenticatedSettingsOtelRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/adapters/': typeof AuthenticatedAdaptersIndexRoute
  '/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/fleet/': typeof AuthenticatedFleetIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/agents/$id/benchmarks': typeof AuthenticatedAgentsIdBenchmarksRouteWithChildren
  '/agents/$id/channels': typeof AuthenticatedAgentsIdChannelsRoute
  '/agents/$id/circuit-breaker': typeof AuthenticatedAgentsIdCircuitBreakerRoute
  '/agents/$id/compliance': typeof AuthenticatedAgentsIdComplianceRoute
  '/agents/$id/config': typeof AuthenticatedAgentsIdConfigRoute
  '/agents/$id/conversations': typeof AuthenticatedAgentsIdConversationsRouteWithChildren
  '/agents/$id/cron': typeof AuthenticatedAgentsIdCronRoute
  '/agents/$id/evaluation': typeof AuthenticatedAgentsIdEvaluationRoute
  '/agents/$id/handoffs': typeof AuthenticatedAgentsIdHandoffsRoute
  '/agents/$id/knowledge': typeof AuthenticatedAgentsIdKnowledgeRoute
  '/agents/$id/mcp-tools': typeof AuthenticatedAgentsIdMcpToolsRoute
  '/agents/$id/memory': typeof AuthenticatedAgentsIdMemoryRoute
  '/agents/$id/quality': typeof AuthenticatedAgentsIdQualityRoute
  '/agents/$id/quotas': typeof AuthenticatedAgentsIdQuotasRoute
  '/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/agents/$id/routing': typeof AuthenticatedAgentsIdRoutingRoute
  '/agents/$id/sandbox': typeof AuthenticatedAgentsIdSandboxRoute
  '/agents/$id/versions': typeof AuthenticatedAgentsIdVersionsRoute
  '/agents/$id/webhooks': typeof AuthenticatedAgentsIdWebhooksRoute
  '/agents/$id/workflows': typeof AuthenticatedAgentsIdWorkflowsRoute
  '/settings/users/$slug': typeof AuthenticatedSettingsUsersSlugRouteWithChildren
  '/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/agents/$id/conversations/$convId': typeof AuthenticatedAgentsIdConversationsConvIdRoute
  '/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/settings/users/$slug/password': typeof AuthenticatedSettingsUsersSlugPasswordRoute
  '/agents/$id/conversations/': typeof AuthenticatedAgentsIdConversationsIndexRoute
  '/settings/users/$slug/': typeof AuthenticatedSettingsUsersSlugIndexRoute
  '/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transcription': typeof AuthenticatedTranscriptionRoute
  '/': typeof AuthenticatedIndexRoute
  '/adapters/new': typeof AuthenticatedAdaptersNewRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/channels/new': typeof AuthenticatedChannelsNewRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/conversations/new': typeof AuthenticatedConversationsNewRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/settings/otel': typeof AuthenticatedSettingsOtelRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/adapters': typeof AuthenticatedAdaptersIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/agents/$id/benchmarks': typeof AuthenticatedAgentsIdBenchmarksRouteWithChildren
  '/agents/$id/channels': typeof AuthenticatedAgentsIdChannelsRoute
  '/agents/$id/circuit-breaker': typeof AuthenticatedAgentsIdCircuitBreakerRoute
  '/agents/$id/compliance': typeof AuthenticatedAgentsIdComplianceRoute
  '/agents/$id/config': typeof AuthenticatedAgentsIdConfigRoute
  '/agents/$id/cron': typeof AuthenticatedAgentsIdCronRoute
  '/agents/$id/evaluation': typeof AuthenticatedAgentsIdEvaluationRoute
  '/agents/$id/handoffs': typeof AuthenticatedAgentsIdHandoffsRoute
  '/agents/$id/knowledge': typeof AuthenticatedAgentsIdKnowledgeRoute
  '/agents/$id/mcp-tools': typeof AuthenticatedAgentsIdMcpToolsRoute
  '/agents/$id/memory': typeof AuthenticatedAgentsIdMemoryRoute
  '/agents/$id/quality': typeof AuthenticatedAgentsIdQualityRoute
  '/agents/$id/quotas': typeof AuthenticatedAgentsIdQuotasRoute
  '/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/agents/$id/routing': typeof AuthenticatedAgentsIdRoutingRoute
  '/agents/$id/sandbox': typeof AuthenticatedAgentsIdSandboxRoute
  '/agents/$id/versions': typeof AuthenticatedAgentsIdVersionsRoute
  '/agents/$id/webhooks': typeof AuthenticatedAgentsIdWebhooksRoute
  '/agents/$id/workflows': typeof AuthenticatedAgentsIdWorkflowsRoute
  '/agents/$id': typeof AuthenticatedAgentsIdIndexRoute
  '/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/agents/$id/conversations/$convId': typeof AuthenticatedAgentsIdConversationsConvIdRoute
  '/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/settings/users/$slug/password': typeof AuthenticatedSettingsUsersSlugPasswordRoute
  '/agents/$id/conversations': typeof AuthenticatedAgentsIdConversationsIndexRoute
  '/settings/users/$slug': typeof AuthenticatedSettingsUsersSlugIndexRoute
  '/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/adapters': typeof AuthenticatedAdaptersRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/cron': typeof AuthenticatedCronRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ratings': typeof AuthenticatedRatingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transcription': typeof AuthenticatedTranscriptionRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/adapters/new': typeof AuthenticatedAdaptersNewRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/_authenticated/channels/new': typeof AuthenticatedChannelsNewRoute
  '/_authenticated/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/_authenticated/conversations/new': typeof AuthenticatedConversationsNewRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/settings_/otel': typeof AuthenticatedSettingsOtelRoute
  '/_authenticated/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/_authenticated/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/_authenticated/adapters/': typeof AuthenticatedAdaptersIndexRoute
  '/_authenticated/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/fleet/': typeof AuthenticatedFleetIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/agents/$id/benchmarks': typeof AuthenticatedAgentsIdBenchmarksRouteWithChildren
  '/_authenticated/agents/$id/channels': typeof AuthenticatedAgentsIdChannelsRoute
  '/_authenticated/agents/$id/circuit-breaker': typeof AuthenticatedAgentsIdCircuitBreakerRoute
  '/_authenticated/agents/$id/compliance': typeof AuthenticatedAgentsIdComplianceRoute
  '/_authenticated/agents/$id/config': typeof AuthenticatedAgentsIdConfigRoute
  '/_authenticated/agents/$id/conversations': typeof AuthenticatedAgentsIdConversationsRouteWithChildren
  '/_authenticated/agents/$id/cron': typeof AuthenticatedAgentsIdCronRoute
  '/_authenticated/agents/$id/evaluation': typeof AuthenticatedAgentsIdEvaluationRoute
  '/_authenticated/agents/$id/handoffs': typeof AuthenticatedAgentsIdHandoffsRoute
  '/_authenticated/agents/$id/knowledge': typeof AuthenticatedAgentsIdKnowledgeRoute
  '/_authenticated/agents/$id/mcp-tools': typeof AuthenticatedAgentsIdMcpToolsRoute
  '/_authenticated/agents/$id/memory': typeof AuthenticatedAgentsIdMemoryRoute
  '/_authenticated/agents/$id/quality': typeof AuthenticatedAgentsIdQualityRoute
  '/_authenticated/agents/$id/quotas': typeof AuthenticatedAgentsIdQuotasRoute
  '/_authenticated/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/_authenticated/agents/$id/routing': typeof AuthenticatedAgentsIdRoutingRoute
  '/_authenticated/agents/$id/sandbox': typeof AuthenticatedAgentsIdSandboxRoute
  '/_authenticated/agents/$id/versions': typeof AuthenticatedAgentsIdVersionsRoute
  '/_authenticated/agents/$id/webhooks': typeof AuthenticatedAgentsIdWebhooksRoute
  '/_authenticated/agents/$id/workflows': typeof AuthenticatedAgentsIdWorkflowsRoute
  '/_authenticated/settings_/users/$slug': typeof AuthenticatedSettingsUsersSlugRouteWithChildren
  '/_authenticated/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
  '/_authenticated/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/_authenticated/agents/$id/conversations/$convId': typeof AuthenticatedAgentsIdConversationsConvIdRoute
  '/_authenticated/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/_authenticated/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/_authenticated/settings_/users/$slug/password': typeof AuthenticatedSettingsUsersSlugPasswordRoute
  '/_authenticated/agents/$id/conversations/': typeof AuthenticatedAgentsIdConversationsIndexRoute
  '/_authenticated/settings_/users/$slug/': typeof AuthenticatedSettingsUsersSlugIndexRoute
  '/_authenticated/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/adapters'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/conversations'
    | '/costs'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/ratings'
    | '/settings'
    | '/transcription'
    | '/workflows'
    | '/adapters/new'
    | '/agents/$id'
    | '/agents/new'
    | '/channels/$slug'
    | '/channels/new'
    | '/conversations/$id'
    | '/conversations/new'
    | '/jobs/$id'
    | '/settings/otel'
    | '/workflows/$id'
    | '/workflows/new'
    | '/adapters/'
    | '/approvals/'
    | '/channels/'
    | '/compliance/'
    | '/conversations/'
    | '/fleet/'
    | '/inbox/'
    | '/security/'
    | '/workflows/'
    | '/agents/$id/benchmarks'
    | '/agents/$id/channels'
    | '/agents/$id/circuit-breaker'
    | '/agents/$id/compliance'
    | '/agents/$id/config'
    | '/agents/$id/conversations'
    | '/agents/$id/cron'
    | '/agents/$id/evaluation'
    | '/agents/$id/handoffs'
    | '/agents/$id/knowledge'
    | '/agents/$id/mcp-tools'
    | '/agents/$id/memory'
    | '/agents/$id/quality'
    | '/agents/$id/quotas'
    | '/agents/$id/ratings'
    | '/agents/$id/routing'
    | '/agents/$id/sandbox'
    | '/agents/$id/versions'
    | '/agents/$id/webhooks'
    | '/agents/$id/workflows'
    | '/settings/users/$slug'
    | '/agents/$id/'
    | '/agents/$id/benchmarks/$runId'
    | '/agents/$id/conversations/$convId'
    | '/agents/$id/drafts/$draftId'
    | '/agents/$id/eval-runs/$runId'
    | '/settings/users/$slug/password'
    | '/agents/$id/conversations/'
    | '/settings/users/$slug/'
    | '/agents/$id/drafts/$draftId/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/costs'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/ratings'
    | '/settings'
    | '/transcription'
    | '/'
    | '/adapters/new'
    | '/agents/new'
    | '/channels/$slug'
    | '/channels/new'
    | '/conversations/$id'
    | '/conversations/new'
    | '/jobs/$id'
    | '/settings/otel'
    | '/workflows/$id'
    | '/workflows/new'
    | '/adapters'
    | '/approvals'
    | '/channels'
    | '/compliance'
    | '/conversations'
    | '/fleet'
    | '/inbox'
    | '/security'
    | '/workflows'
    | '/agents/$id/benchmarks'
    | '/agents/$id/channels'
    | '/agents/$id/circuit-breaker'
    | '/agents/$id/compliance'
    | '/agents/$id/config'
    | '/agents/$id/cron'
    | '/agents/$id/evaluation'
    | '/agents/$id/handoffs'
    | '/agents/$id/knowledge'
    | '/agents/$id/mcp-tools'
    | '/agents/$id/memory'
    | '/agents/$id/quality'
    | '/agents/$id/quotas'
    | '/agents/$id/ratings'
    | '/agents/$id/routing'
    | '/agents/$id/sandbox'
    | '/agents/$id/versions'
    | '/agents/$id/webhooks'
    | '/agents/$id/workflows'
    | '/agents/$id'
    | '/agents/$id/benchmarks/$runId'
    | '/agents/$id/conversations/$convId'
    | '/agents/$id/drafts/$draftId'
    | '/agents/$id/eval-runs/$runId'
    | '/settings/users/$slug/password'
    | '/agents/$id/conversations'
    | '/settings/users/$slug'
    | '/agents/$id/drafts/$draftId/compare'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/adapters'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/channels'
    | '/_authenticated/conversations'
    | '/_authenticated/costs'
    | '/_authenticated/cron'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/ratings'
    | '/_authenticated/settings'
    | '/_authenticated/transcription'
    | '/_authenticated/workflows'
    | '/_authenticated/'
    | '/_authenticated/adapters/new'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/channels/$slug'
    | '/_authenticated/channels/new'
    | '/_authenticated/conversations/$id'
    | '/_authenticated/conversations/new'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/settings_/otel'
    | '/_authenticated/workflows/$id'
    | '/_authenticated/workflows/new'
    | '/_authenticated/adapters/'
    | '/_authenticated/approvals/'
    | '/_authenticated/channels/'
    | '/_authenticated/compliance/'
    | '/_authenticated/conversations/'
    | '/_authenticated/fleet/'
    | '/_authenticated/inbox/'
    | '/_authenticated/security/'
    | '/_authenticated/workflows/'
    | '/_authenticated/agents/$id/benchmarks'
    | '/_authenticated/agents/$id/channels'
    | '/_authenticated/agents/$id/circuit-breaker'
    | '/_authenticated/agents/$id/compliance'
    | '/_authenticated/agents/$id/config'
    | '/_authenticated/agents/$id/conversations'
    | '/_authenticated/agents/$id/cron'
    | '/_authenticated/agents/$id/evaluation'
    | '/_authenticated/agents/$id/handoffs'
    | '/_authenticated/agents/$id/knowledge'
    | '/_authenticated/agents/$id/mcp-tools'
    | '/_authenticated/agents/$id/memory'
    | '/_authenticated/agents/$id/quality'
    | '/_authenticated/agents/$id/quotas'
    | '/_authenticated/agents/$id/ratings'
    | '/_authenticated/agents/$id/routing'
    | '/_authenticated/agents/$id/sandbox'
    | '/_authenticated/agents/$id/versions'
    | '/_authenticated/agents/$id/webhooks'
    | '/_authenticated/agents/$id/workflows'
    | '/_authenticated/settings_/users/$slug'
    | '/_authenticated/agents/$id/'
    | '/_authenticated/agents/$id/benchmarks/$runId'
    | '/_authenticated/agents/$id/conversations/$convId'
    | '/_authenticated/agents/$id/drafts/$draftId'
    | '/_authenticated/agents/$id/eval-runs/$runId'
    | '/_authenticated/settings_/users/$slug/password'
    | '/_authenticated/agents/$id/conversations/'
    | '/_authenticated/settings_/users/$slug/'
    | '/_authenticated/agents/$id/drafts/$draftId/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transcription': {
      id: '/_authenticated/transcription'
      path: '/transcription'
      fullPath: '/transcription'
      preLoaderRoute: typeof AuthenticatedTranscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ratings': {
      id: '/_authenticated/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AuthenticatedRatingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cron': {
      id: '/_authenticated/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AuthenticatedCronRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adapters': {
      id: '/_authenticated/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AuthenticatedAdaptersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet/': {
      id: '/_authenticated/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AuthenticatedFleetIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/approvals/': {
      id: '/_authenticated/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthenticatedApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adapters/': {
      id: '/_authenticated/adapters/'
      path: '/'
      fullPath: '/adapters/'
      preLoaderRoute: typeof AuthenticatedAdaptersIndexRouteImport
      parentRoute: typeof AuthenticatedAdaptersRoute
    }
    '/_authenticated/workflows/new': {
      id: '/_authenticated/workflows/new'
      path: '/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AuthenticatedWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/workflows/$id': {
      id: '/_authenticated/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/settings_/otel': {
      id: '/_authenticated/settings_/otel'
      path: '/settings/otel'
      fullPath: '/settings/otel'
      preLoaderRoute: typeof AuthenticatedSettingsOtelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/conversations/new': {
      id: '/_authenticated/conversations/new'
      path: '/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthenticatedConversationsNewRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/conversations/$id': {
      id: '/_authenticated/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConversationsIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/channels/new': {
      id: '/_authenticated/channels/new'
      path: '/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof AuthenticatedChannelsNewRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/$slug': {
      id: '/_authenticated/channels/$slug'
      path: '/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof AuthenticatedChannelsSlugRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/adapters/new': {
      id: '/_authenticated/adapters/new'
      path: '/new'
      fullPath: '/adapters/new'
      preLoaderRoute: typeof AuthenticatedAdaptersNewRouteImport
      parentRoute: typeof AuthenticatedAdaptersRoute
    }
    '/_authenticated/agents/$id/': {
      id: '/_authenticated/agents/$id/'
      path: '/'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AuthenticatedAgentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/settings_/users/$slug': {
      id: '/_authenticated/settings_/users/$slug'
      path: '/settings/users/$slug'
      fullPath: '/settings/users/$slug'
      preLoaderRoute: typeof AuthenticatedSettingsUsersSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/$id/workflows': {
      id: '/_authenticated/agents/$id/workflows'
      path: '/workflows'
      fullPath: '/agents/$id/workflows'
      preLoaderRoute: typeof AuthenticatedAgentsIdWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/webhooks': {
      id: '/_authenticated/agents/$id/webhooks'
      path: '/webhooks'
      fullPath: '/agents/$id/webhooks'
      preLoaderRoute: typeof AuthenticatedAgentsIdWebhooksRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/versions': {
      id: '/_authenticated/agents/$id/versions'
      path: '/versions'
      fullPath: '/agents/$id/versions'
      preLoaderRoute: typeof AuthenticatedAgentsIdVersionsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/sandbox': {
      id: '/_authenticated/agents/$id/sandbox'
      path: '/sandbox'
      fullPath: '/agents/$id/sandbox'
      preLoaderRoute: typeof AuthenticatedAgentsIdSandboxRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/routing': {
      id: '/_authenticated/agents/$id/routing'
      path: '/routing'
      fullPath: '/agents/$id/routing'
      preLoaderRoute: typeof AuthenticatedAgentsIdRoutingRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/ratings': {
      id: '/_authenticated/agents/$id/ratings'
      path: '/ratings'
      fullPath: '/agents/$id/ratings'
      preLoaderRoute: typeof AuthenticatedAgentsIdRatingsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/quotas': {
      id: '/_authenticated/agents/$id/quotas'
      path: '/quotas'
      fullPath: '/agents/$id/quotas'
      preLoaderRoute: typeof AuthenticatedAgentsIdQuotasRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/quality': {
      id: '/_authenticated/agents/$id/quality'
      path: '/quality'
      fullPath: '/agents/$id/quality'
      preLoaderRoute: typeof AuthenticatedAgentsIdQualityRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/memory': {
      id: '/_authenticated/agents/$id/memory'
      path: '/memory'
      fullPath: '/agents/$id/memory'
      preLoaderRoute: typeof AuthenticatedAgentsIdMemoryRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/mcp-tools': {
      id: '/_authenticated/agents/$id/mcp-tools'
      path: '/mcp-tools'
      fullPath: '/agents/$id/mcp-tools'
      preLoaderRoute: typeof AuthenticatedAgentsIdMcpToolsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/knowledge': {
      id: '/_authenticated/agents/$id/knowledge'
      path: '/knowledge'
      fullPath: '/agents/$id/knowledge'
      preLoaderRoute: typeof AuthenticatedAgentsIdKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/handoffs': {
      id: '/_authenticated/agents/$id/handoffs'
      path: '/handoffs'
      fullPath: '/agents/$id/handoffs'
      preLoaderRoute: typeof AuthenticatedAgentsIdHandoffsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/evaluation': {
      id: '/_authenticated/agents/$id/evaluation'
      path: '/evaluation'
      fullPath: '/agents/$id/evaluation'
      preLoaderRoute: typeof AuthenticatedAgentsIdEvaluationRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/cron': {
      id: '/_authenticated/agents/$id/cron'
      path: '/cron'
      fullPath: '/agents/$id/cron'
      preLoaderRoute: typeof AuthenticatedAgentsIdCronRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/conversations': {
      id: '/_authenticated/agents/$id/conversations'
      path: '/conversations'
      fullPath: '/agents/$id/conversations'
      preLoaderRoute: typeof AuthenticatedAgentsIdConversationsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/config': {
      id: '/_authenticated/agents/$id/config'
      path: '/config'
      fullPath: '/agents/$id/config'
      preLoaderRoute: typeof AuthenticatedAgentsIdConfigRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/compliance': {
      id: '/_authenticated/agents/$id/compliance'
      path: '/compliance'
      fullPath: '/agents/$id/compliance'
      preLoaderRoute: typeof AuthenticatedAgentsIdComplianceRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/circuit-breaker': {
      id: '/_authenticated/agents/$id/circuit-breaker'
      path: '/circuit-breaker'
      fullPath: '/agents/$id/circuit-breaker'
      preLoaderRoute: typeof AuthenticatedAgentsIdCircuitBreakerRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/channels': {
      id: '/_authenticated/agents/$id/channels'
      path: '/channels'
      fullPath: '/agents/$id/channels'
      preLoaderRoute: typeof AuthenticatedAgentsIdChannelsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/benchmarks': {
      id: '/_authenticated/agents/$id/benchmarks'
      path: '/benchmarks'
      fullPath: '/agents/$id/benchmarks'
      preLoaderRoute: typeof AuthenticatedAgentsIdBenchmarksRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/settings_/users/$slug/': {
      id: '/_authenticated/settings_/users/$slug/'
      path: '/'
      fullPath: '/settings/users/$slug/'
      preLoaderRoute: typeof AuthenticatedSettingsUsersSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsUsersSlugRoute
    }
    '/_authenticated/agents/$id/conversations/': {
      id: '/_authenticated/agents/$id/conversations/'
      path: '/'
      fullPath: '/agents/$id/conversations/'
      preLoaderRoute: typeof AuthenticatedAgentsIdConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdConversationsRoute
    }
    '/_authenticated/settings_/users/$slug/password': {
      id: '/_authenticated/settings_/users/$slug/password'
      path: '/password'
      fullPath: '/settings/users/$slug/password'
      preLoaderRoute: typeof AuthenticatedSettingsUsersSlugPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsUsersSlugRoute
    }
    '/_authenticated/agents/$id/eval-runs/$runId': {
      id: '/_authenticated/agents/$id/eval-runs/$runId'
      path: '/eval-runs/$runId'
      fullPath: '/agents/$id/eval-runs/$runId'
      preLoaderRoute: typeof AuthenticatedAgentsIdEvalRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/drafts/$draftId': {
      id: '/_authenticated/agents/$id/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/agents/$id/drafts/$draftId'
      preLoaderRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/conversations/$convId': {
      id: '/_authenticated/agents/$id/conversations/$convId'
      path: '/$convId'
      fullPath: '/agents/$id/conversations/$convId'
      preLoaderRoute: typeof AuthenticatedAgentsIdConversationsConvIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdConversationsRoute
    }
    '/_authenticated/agents/$id/benchmarks/$runId': {
      id: '/_authenticated/agents/$id/benchmarks/$runId'
      path: '/$runId'
      fullPath: '/agents/$id/benchmarks/$runId'
      preLoaderRoute: typeof AuthenticatedAgentsIdBenchmarksRunIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdBenchmarksRoute
    }
    '/_authenticated/agents/$id/drafts/$draftId/compare': {
      id: '/_authenticated/agents/$id/drafts/$draftId/compare'
      path: '/compare'
      fullPath: '/agents/$id/drafts/$draftId/compare'
      preLoaderRoute: typeof AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport
      parentRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRoute
    }
  }
}

interface AuthenticatedAdaptersRouteChildren {
  AuthenticatedAdaptersNewRoute: typeof AuthenticatedAdaptersNewRoute
  AuthenticatedAdaptersIndexRoute: typeof AuthenticatedAdaptersIndexRoute
}

const AuthenticatedAdaptersRouteChildren: AuthenticatedAdaptersRouteChildren = {
  AuthenticatedAdaptersNewRoute: AuthenticatedAdaptersNewRoute,
  AuthenticatedAdaptersIndexRoute: AuthenticatedAdaptersIndexRoute,
}

const AuthenticatedAdaptersRouteWithChildren =
  AuthenticatedAdaptersRoute._addFileChildren(
    AuthenticatedAdaptersRouteChildren,
  )

interface AuthenticatedAgentsIdBenchmarksRouteChildren {
  AuthenticatedAgentsIdBenchmarksRunIdRoute: typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
}

const AuthenticatedAgentsIdBenchmarksRouteChildren: AuthenticatedAgentsIdBenchmarksRouteChildren =
  {
    AuthenticatedAgentsIdBenchmarksRunIdRoute:
      AuthenticatedAgentsIdBenchmarksRunIdRoute,
  }

const AuthenticatedAgentsIdBenchmarksRouteWithChildren =
  AuthenticatedAgentsIdBenchmarksRoute._addFileChildren(
    AuthenticatedAgentsIdBenchmarksRouteChildren,
  )

interface AuthenticatedAgentsIdConversationsRouteChildren {
  AuthenticatedAgentsIdConversationsConvIdRoute: typeof AuthenticatedAgentsIdConversationsConvIdRoute
  AuthenticatedAgentsIdConversationsIndexRoute: typeof AuthenticatedAgentsIdConversationsIndexRoute
}

const AuthenticatedAgentsIdConversationsRouteChildren: AuthenticatedAgentsIdConversationsRouteChildren =
  {
    AuthenticatedAgentsIdConversationsConvIdRoute:
      AuthenticatedAgentsIdConversationsConvIdRoute,
    AuthenticatedAgentsIdConversationsIndexRoute:
      AuthenticatedAgentsIdConversationsIndexRoute,
  }

const AuthenticatedAgentsIdConversationsRouteWithChildren =
  AuthenticatedAgentsIdConversationsRoute._addFileChildren(
    AuthenticatedAgentsIdConversationsRouteChildren,
  )

interface AuthenticatedAgentsIdDraftsDraftIdRouteChildren {
  AuthenticatedAgentsIdDraftsDraftIdCompareRoute: typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}

const AuthenticatedAgentsIdDraftsDraftIdRouteChildren: AuthenticatedAgentsIdDraftsDraftIdRouteChildren =
  {
    AuthenticatedAgentsIdDraftsDraftIdCompareRoute:
      AuthenticatedAgentsIdDraftsDraftIdCompareRoute,
  }

const AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren =
  AuthenticatedAgentsIdDraftsDraftIdRoute._addFileChildren(
    AuthenticatedAgentsIdDraftsDraftIdRouteChildren,
  )

interface AuthenticatedAgentsIdRouteChildren {
  AuthenticatedAgentsIdBenchmarksRoute: typeof AuthenticatedAgentsIdBenchmarksRouteWithChildren
  AuthenticatedAgentsIdChannelsRoute: typeof AuthenticatedAgentsIdChannelsRoute
  AuthenticatedAgentsIdCircuitBreakerRoute: typeof AuthenticatedAgentsIdCircuitBreakerRoute
  AuthenticatedAgentsIdComplianceRoute: typeof AuthenticatedAgentsIdComplianceRoute
  AuthenticatedAgentsIdConfigRoute: typeof AuthenticatedAgentsIdConfigRoute
  AuthenticatedAgentsIdConversationsRoute: typeof AuthenticatedAgentsIdConversationsRouteWithChildren
  AuthenticatedAgentsIdCronRoute: typeof AuthenticatedAgentsIdCronRoute
  AuthenticatedAgentsIdEvaluationRoute: typeof AuthenticatedAgentsIdEvaluationRoute
  AuthenticatedAgentsIdHandoffsRoute: typeof AuthenticatedAgentsIdHandoffsRoute
  AuthenticatedAgentsIdKnowledgeRoute: typeof AuthenticatedAgentsIdKnowledgeRoute
  AuthenticatedAgentsIdMcpToolsRoute: typeof AuthenticatedAgentsIdMcpToolsRoute
  AuthenticatedAgentsIdMemoryRoute: typeof AuthenticatedAgentsIdMemoryRoute
  AuthenticatedAgentsIdQualityRoute: typeof AuthenticatedAgentsIdQualityRoute
  AuthenticatedAgentsIdQuotasRoute: typeof AuthenticatedAgentsIdQuotasRoute
  AuthenticatedAgentsIdRatingsRoute: typeof AuthenticatedAgentsIdRatingsRoute
  AuthenticatedAgentsIdRoutingRoute: typeof AuthenticatedAgentsIdRoutingRoute
  AuthenticatedAgentsIdSandboxRoute: typeof AuthenticatedAgentsIdSandboxRoute
  AuthenticatedAgentsIdVersionsRoute: typeof AuthenticatedAgentsIdVersionsRoute
  AuthenticatedAgentsIdWebhooksRoute: typeof AuthenticatedAgentsIdWebhooksRoute
  AuthenticatedAgentsIdWorkflowsRoute: typeof AuthenticatedAgentsIdWorkflowsRoute
  AuthenticatedAgentsIdIndexRoute: typeof AuthenticatedAgentsIdIndexRoute
  AuthenticatedAgentsIdDraftsDraftIdRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  AuthenticatedAgentsIdEvalRunsRunIdRoute: typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
}

const AuthenticatedAgentsIdRouteChildren: AuthenticatedAgentsIdRouteChildren = {
  AuthenticatedAgentsIdBenchmarksRoute:
    AuthenticatedAgentsIdBenchmarksRouteWithChildren,
  AuthenticatedAgentsIdChannelsRoute: AuthenticatedAgentsIdChannelsRoute,
  AuthenticatedAgentsIdCircuitBreakerRoute:
    AuthenticatedAgentsIdCircuitBreakerRoute,
  AuthenticatedAgentsIdComplianceRoute: AuthenticatedAgentsIdComplianceRoute,
  AuthenticatedAgentsIdConfigRoute: AuthenticatedAgentsIdConfigRoute,
  AuthenticatedAgentsIdConversationsRoute:
    AuthenticatedAgentsIdConversationsRouteWithChildren,
  AuthenticatedAgentsIdCronRoute: AuthenticatedAgentsIdCronRoute,
  AuthenticatedAgentsIdEvaluationRoute: AuthenticatedAgentsIdEvaluationRoute,
  AuthenticatedAgentsIdHandoffsRoute: AuthenticatedAgentsIdHandoffsRoute,
  AuthenticatedAgentsIdKnowledgeRoute: AuthenticatedAgentsIdKnowledgeRoute,
  AuthenticatedAgentsIdMcpToolsRoute: AuthenticatedAgentsIdMcpToolsRoute,
  AuthenticatedAgentsIdMemoryRoute: AuthenticatedAgentsIdMemoryRoute,
  AuthenticatedAgentsIdQualityRoute: AuthenticatedAgentsIdQualityRoute,
  AuthenticatedAgentsIdQuotasRoute: AuthenticatedAgentsIdQuotasRoute,
  AuthenticatedAgentsIdRatingsRoute: AuthenticatedAgentsIdRatingsRoute,
  AuthenticatedAgentsIdRoutingRoute: AuthenticatedAgentsIdRoutingRoute,
  AuthenticatedAgentsIdSandboxRoute: AuthenticatedAgentsIdSandboxRoute,
  AuthenticatedAgentsIdVersionsRoute: AuthenticatedAgentsIdVersionsRoute,
  AuthenticatedAgentsIdWebhooksRoute: AuthenticatedAgentsIdWebhooksRoute,
  AuthenticatedAgentsIdWorkflowsRoute: AuthenticatedAgentsIdWorkflowsRoute,
  AuthenticatedAgentsIdIndexRoute: AuthenticatedAgentsIdIndexRoute,
  AuthenticatedAgentsIdDraftsDraftIdRoute:
    AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren,
  AuthenticatedAgentsIdEvalRunsRunIdRoute:
    AuthenticatedAgentsIdEvalRunsRunIdRoute,
}

const AuthenticatedAgentsIdRouteWithChildren =
  AuthenticatedAgentsIdRoute._addFileChildren(
    AuthenticatedAgentsIdRouteChildren,
  )

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRouteWithChildren
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRouteWithChildren,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsSlugRoute: typeof AuthenticatedChannelsSlugRoute
  AuthenticatedChannelsNewRoute: typeof AuthenticatedChannelsNewRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsSlugRoute: AuthenticatedChannelsSlugRoute,
  AuthenticatedChannelsNewRoute: AuthenticatedChannelsNewRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsIdRoute: typeof AuthenticatedConversationsIdRoute
  AuthenticatedConversationsNewRoute: typeof AuthenticatedConversationsNewRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsIdRoute: AuthenticatedConversationsIdRoute,
    AuthenticatedConversationsNewRoute: AuthenticatedConversationsNewRoute,
    AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedWorkflowsRouteChildren {
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRoute
  AuthenticatedWorkflowsNewRoute: typeof AuthenticatedWorkflowsNewRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedWorkflowsRouteChildren: AuthenticatedWorkflowsRouteChildren =
  {
    AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRoute,
    AuthenticatedWorkflowsNewRoute: AuthenticatedWorkflowsNewRoute,
    AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  }

const AuthenticatedWorkflowsRouteWithChildren =
  AuthenticatedWorkflowsRoute._addFileChildren(
    AuthenticatedWorkflowsRouteChildren,
  )

interface AuthenticatedSettingsUsersSlugRouteChildren {
  AuthenticatedSettingsUsersSlugPasswordRoute: typeof AuthenticatedSettingsUsersSlugPasswordRoute
  AuthenticatedSettingsUsersSlugIndexRoute: typeof AuthenticatedSettingsUsersSlugIndexRoute
}

const AuthenticatedSettingsUsersSlugRouteChildren: AuthenticatedSettingsUsersSlugRouteChildren =
  {
    AuthenticatedSettingsUsersSlugPasswordRoute:
      AuthenticatedSettingsUsersSlugPasswordRoute,
    AuthenticatedSettingsUsersSlugIndexRoute:
      AuthenticatedSettingsUsersSlugIndexRoute,
  }

const AuthenticatedSettingsUsersSlugRouteWithChildren =
  AuthenticatedSettingsUsersSlugRoute._addFileChildren(
    AuthenticatedSettingsUsersSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdaptersRoute: typeof AuthenticatedAdaptersRouteWithChildren
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedCronRoute: typeof AuthenticatedCronRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRatingsRoute: typeof AuthenticatedRatingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTranscriptionRoute: typeof AuthenticatedTranscriptionRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsOtelRoute: typeof AuthenticatedSettingsOtelRoute
  AuthenticatedApprovalsIndexRoute: typeof AuthenticatedApprovalsIndexRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedFleetIndexRoute: typeof AuthenticatedFleetIndexRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedSettingsUsersSlugRoute: typeof AuthenticatedSettingsUsersSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdaptersRoute: AuthenticatedAdaptersRouteWithChildren,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedCronRoute: AuthenticatedCronRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRatingsRoute: AuthenticatedRatingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTranscriptionRoute: AuthenticatedTranscriptionRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsOtelRoute: AuthenticatedSettingsOtelRoute,
  AuthenticatedApprovalsIndexRoute: AuthenticatedApprovalsIndexRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  AuthenticatedFleetIndexRoute: AuthenticatedFleetIndexRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedSettingsUsersSlugRoute:
    AuthenticatedSettingsUsersSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
