/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRatingsRouteImport } from './routes/_authenticated/ratings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedCronRouteImport } from './routes/_authenticated/cron'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedApprovalsIndexRouteImport } from './routes/_authenticated/approvals/index'
import { Route as AuthenticatedAdaptersIndexRouteImport } from './routes/_authenticated/adapters/index'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows.$id'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedConversationsIdRouteImport } from './routes/_authenticated/conversations.$id'
import { Route as AuthenticatedChannelsSlugRouteImport } from './routes/_authenticated/channels.$slug'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAgentsIdRatingsRouteImport } from './routes/_authenticated/agents.$id.ratings'
import { Route as AuthenticatedAgentsIdEvalRunsRunIdRouteImport } from './routes/_authenticated/agents.$id.eval-runs.$runId'
import { Route as AuthenticatedAgentsIdDraftsDraftIdRouteImport } from './routes/_authenticated/agents.$id.drafts.$draftId'
import { Route as AuthenticatedAgentsIdBenchmarksRunIdRouteImport } from './routes/_authenticated/agents.$id.benchmarks.$runId'
import { Route as AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport } from './routes/_authenticated/agents.$id.drafts.$draftId.compare'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatingsRoute = AuthenticatedRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCronRoute = AuthenticatedCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsIndexRoute =
  AuthenticatedApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdaptersIndexRoute =
  AuthenticatedAdaptersIndexRouteImport.update({
    id: '/adapters/',
    path: '/adapters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedConversationsIdRoute =
  AuthenticatedConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedChannelsSlugRoute =
  AuthenticatedChannelsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAgentsIdRatingsRoute =
  AuthenticatedAgentsIdRatingsRouteImport.update({
    id: '/ratings',
    path: '/ratings',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdEvalRunsRunIdRoute =
  AuthenticatedAgentsIdEvalRunsRunIdRouteImport.update({
    id: '/eval-runs/$runId',
    path: '/eval-runs/$runId',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdDraftsDraftIdRoute =
  AuthenticatedAgentsIdDraftsDraftIdRouteImport.update({
    id: '/drafts/$draftId',
    path: '/drafts/$draftId',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdBenchmarksRunIdRoute =
  AuthenticatedAgentsIdBenchmarksRunIdRouteImport.update({
    id: '/benchmarks/$runId',
    path: '/benchmarks/$runId',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const AuthenticatedAgentsIdDraftsDraftIdCompareRoute =
  AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedAgentsIdDraftsDraftIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/costs': typeof AuthenticatedCostsRoute
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/adapters/': typeof AuthenticatedAdaptersIndexRoute
  '/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/costs': typeof AuthenticatedCostsRoute
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/adapters': typeof AuthenticatedAdaptersIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/cron': typeof AuthenticatedCronRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ratings': typeof AuthenticatedRatingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/_authenticated/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/_authenticated/adapters/': typeof AuthenticatedAdaptersIndexRoute
  '/_authenticated/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/agents/$id/ratings': typeof AuthenticatedAgentsIdRatingsRoute
  '/_authenticated/agents/$id/benchmarks/$runId': typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  '/_authenticated/agents/$id/drafts/$draftId': typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  '/_authenticated/agents/$id/eval-runs/$runId': typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
  '/_authenticated/agents/$id/drafts/$draftId/compare': typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/conversations'
    | '/costs'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/ratings'
    | '/settings'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/channels/$slug'
    | '/conversations/$id'
    | '/jobs/$id'
    | '/workflows/$id'
    | '/adapters/'
    | '/approvals/'
    | '/inbox/'
    | '/security/'
    | '/compliance/'
    | '/agents/$id/ratings'
    | '/agents/$id/benchmarks/$runId'
    | '/agents/$id/drafts/$draftId'
    | '/agents/$id/eval-runs/$runId'
    | '/agents/$id/drafts/$draftId/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/conversations'
    | '/costs'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/ratings'
    | '/settings'
    | '/workflows'
    | '/'
    | '/agents/$id'
    | '/agents/new'
    | '/channels/$slug'
    | '/conversations/$id'
    | '/jobs/$id'
    | '/workflows/$id'
    | '/adapters'
    | '/approvals'
    | '/inbox'
    | '/security'
    | '/compliance'
    | '/agents/$id/ratings'
    | '/agents/$id/benchmarks/$runId'
    | '/agents/$id/drafts/$draftId'
    | '/agents/$id/eval-runs/$runId'
    | '/agents/$id/drafts/$draftId/compare'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/channels'
    | '/_authenticated/conversations'
    | '/_authenticated/costs'
    | '/_authenticated/cron'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/ratings'
    | '/_authenticated/settings'
    | '/_authenticated/workflows'
    | '/_authenticated/'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/channels/$slug'
    | '/_authenticated/conversations/$id'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/workflows/$id'
    | '/_authenticated/adapters/'
    | '/_authenticated/approvals/'
    | '/_authenticated/inbox/'
    | '/_authenticated/security/'
    | '/_authenticated/compliance/'
    | '/_authenticated/agents/$id/ratings'
    | '/_authenticated/agents/$id/benchmarks/$runId'
    | '/_authenticated/agents/$id/drafts/$draftId'
    | '/_authenticated/agents/$id/eval-runs/$runId'
    | '/_authenticated/agents/$id/drafts/$draftId/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ratings': {
      id: '/_authenticated/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AuthenticatedRatingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cron': {
      id: '/_authenticated/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AuthenticatedCronRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals/': {
      id: '/_authenticated/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthenticatedApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adapters/': {
      id: '/_authenticated/adapters/'
      path: '/adapters'
      fullPath: '/adapters/'
      preLoaderRoute: typeof AuthenticatedAdaptersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$id': {
      id: '/_authenticated/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/conversations/$id': {
      id: '/_authenticated/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConversationsIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/channels/$slug': {
      id: '/_authenticated/channels/$slug'
      path: '/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof AuthenticatedChannelsSlugRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/agents/$id/ratings': {
      id: '/_authenticated/agents/$id/ratings'
      path: '/ratings'
      fullPath: '/agents/$id/ratings'
      preLoaderRoute: typeof AuthenticatedAgentsIdRatingsRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/eval-runs/$runId': {
      id: '/_authenticated/agents/$id/eval-runs/$runId'
      path: '/eval-runs/$runId'
      fullPath: '/agents/$id/eval-runs/$runId'
      preLoaderRoute: typeof AuthenticatedAgentsIdEvalRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/drafts/$draftId': {
      id: '/_authenticated/agents/$id/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/agents/$id/drafts/$draftId'
      preLoaderRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/benchmarks/$runId': {
      id: '/_authenticated/agents/$id/benchmarks/$runId'
      path: '/benchmarks/$runId'
      fullPath: '/agents/$id/benchmarks/$runId'
      preLoaderRoute: typeof AuthenticatedAgentsIdBenchmarksRunIdRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_authenticated/agents/$id/drafts/$draftId/compare': {
      id: '/_authenticated/agents/$id/drafts/$draftId/compare'
      path: '/compare'
      fullPath: '/agents/$id/drafts/$draftId/compare'
      preLoaderRoute: typeof AuthenticatedAgentsIdDraftsDraftIdCompareRouteImport
      parentRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRoute
    }
  }
}

interface AuthenticatedAgentsIdDraftsDraftIdRouteChildren {
  AuthenticatedAgentsIdDraftsDraftIdCompareRoute: typeof AuthenticatedAgentsIdDraftsDraftIdCompareRoute
}

const AuthenticatedAgentsIdDraftsDraftIdRouteChildren: AuthenticatedAgentsIdDraftsDraftIdRouteChildren =
  {
    AuthenticatedAgentsIdDraftsDraftIdCompareRoute:
      AuthenticatedAgentsIdDraftsDraftIdCompareRoute,
  }

const AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren =
  AuthenticatedAgentsIdDraftsDraftIdRoute._addFileChildren(
    AuthenticatedAgentsIdDraftsDraftIdRouteChildren,
  )

interface AuthenticatedAgentsIdRouteChildren {
  AuthenticatedAgentsIdRatingsRoute: typeof AuthenticatedAgentsIdRatingsRoute
  AuthenticatedAgentsIdBenchmarksRunIdRoute: typeof AuthenticatedAgentsIdBenchmarksRunIdRoute
  AuthenticatedAgentsIdDraftsDraftIdRoute: typeof AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren
  AuthenticatedAgentsIdEvalRunsRunIdRoute: typeof AuthenticatedAgentsIdEvalRunsRunIdRoute
}

const AuthenticatedAgentsIdRouteChildren: AuthenticatedAgentsIdRouteChildren = {
  AuthenticatedAgentsIdRatingsRoute: AuthenticatedAgentsIdRatingsRoute,
  AuthenticatedAgentsIdBenchmarksRunIdRoute:
    AuthenticatedAgentsIdBenchmarksRunIdRoute,
  AuthenticatedAgentsIdDraftsDraftIdRoute:
    AuthenticatedAgentsIdDraftsDraftIdRouteWithChildren,
  AuthenticatedAgentsIdEvalRunsRunIdRoute:
    AuthenticatedAgentsIdEvalRunsRunIdRoute,
}

const AuthenticatedAgentsIdRouteWithChildren =
  AuthenticatedAgentsIdRoute._addFileChildren(
    AuthenticatedAgentsIdRouteChildren,
  )

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRouteWithChildren
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRouteWithChildren,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsSlugRoute: typeof AuthenticatedChannelsSlugRoute
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsSlugRoute: AuthenticatedChannelsSlugRoute,
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsIdRoute: typeof AuthenticatedConversationsIdRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsIdRoute: AuthenticatedConversationsIdRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedWorkflowsRouteChildren {
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRoute
}

const AuthenticatedWorkflowsRouteChildren: AuthenticatedWorkflowsRouteChildren =
  {
    AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRoute,
  }

const AuthenticatedWorkflowsRouteWithChildren =
  AuthenticatedWorkflowsRoute._addFileChildren(
    AuthenticatedWorkflowsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedCronRoute: typeof AuthenticatedCronRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRatingsRoute: typeof AuthenticatedRatingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdaptersIndexRoute: typeof AuthenticatedAdaptersIndexRoute
  AuthenticatedApprovalsIndexRoute: typeof AuthenticatedApprovalsIndexRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedCronRoute: AuthenticatedCronRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRatingsRoute: AuthenticatedRatingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdaptersIndexRoute: AuthenticatedAdaptersIndexRoute,
  AuthenticatedApprovalsIndexRoute: AuthenticatedApprovalsIndexRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
