/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedCronRouteImport } from './routes/_authenticated/cron'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedConversationsIdRouteImport } from './routes/_authenticated/conversations.$id'
import { Route as AuthenticatedChannelsSlugRouteImport } from './routes/_authenticated/channels.$slug'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCronRoute = AuthenticatedCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedConversationsIdRoute =
  AuthenticatedConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedChannelsSlugRoute =
  AuthenticatedChannelsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/cron': typeof AuthenticatedCronRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/cron': typeof AuthenticatedCronRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/channels/$slug': typeof AuthenticatedChannelsSlugRoute
  '/_authenticated/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/channels'
    | '/conversations'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/channels/$slug'
    | '/conversations/$id'
    | '/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agents'
    | '/channels'
    | '/conversations'
    | '/cron'
    | '/jobs'
    | '/notifications'
    | '/settings'
    | '/'
    | '/agents/$id'
    | '/agents/new'
    | '/channels/$slug'
    | '/conversations/$id'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agents'
    | '/_authenticated/channels'
    | '/_authenticated/conversations'
    | '/_authenticated/cron'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/channels/$slug'
    | '/_authenticated/conversations/$id'
    | '/_authenticated/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cron': {
      id: '/_authenticated/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AuthenticatedCronRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/conversations/$id': {
      id: '/_authenticated/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConversationsIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/channels/$slug': {
      id: '/_authenticated/channels/$slug'
      path: '/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof AuthenticatedChannelsSlugRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsSlugRoute: typeof AuthenticatedChannelsSlugRoute
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsSlugRoute: AuthenticatedChannelsSlugRoute,
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsIdRoute: typeof AuthenticatedConversationsIdRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsIdRoute: AuthenticatedConversationsIdRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedCronRoute: typeof AuthenticatedCronRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedCronRoute: AuthenticatedCronRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
